### 회원가입
POST {{host}}/member/register
Content-Type: application/json

{
  "loginId": "{{loginId}}",
  "password": "{{password}}"
}


### 로그인
POST {{host}}/member/login
Content-Type: application/json

{
  "loginId": "{{loginId}}",
  "password": "{{password}}"
}

### 카테고리 조회
GET {{host}}/category


### 카테고리 추가
POST {{host}}/category/add
Content-Type: application/json

{
  "name": "categoryAdd"
}

### 카테고리 삭제
DELETE {{host}}/category/1/delete