### 회원가입
POST {{host}}/member/register
Content-Type: application/json

{
  "loginId": "{{loginId}}",
  "password": "{{password}}"
}

### 로그인
POST {{host}}/member/login
Content-Type: application/json

{
  "loginId": "{{loginId}}",
  "password": "{{password}}"
}

### 비밀번호 변경
PUT {{host}}/member/password
Content-Type: application/json

{
  "currentPwd" : "1234",
  "changePwd" : "0000"
}

### 회원 삭제
DELETE {{host}}/member/delete


