### 회원가입
POST {{host}}/member/register
Content-Type: application/json

{
  "loginId": "{{loginId}}",
  "password": "{{password}}"
}

### 로그인
POST {{host}}/member/login
Content-Type: application/json

{
  "loginId": "{{loginId}}",
  "password": "{{password}}"
}

### 노트를 가져오기
GET {{host}}/note


### 노트를 생성하기
POST {{host}}/note/write
Content-Type: application/json

{
  "content": "노트를 생성합니다",
  "categoryId": "1"
}

### 노트에 컨텐츠가 변경
PUT {{host}}/note/3/edit
Content-Type: application/json

{
  "content": "노트가 바껴랏!!",
  "categoryId": "1"
}


### 노트를 삭제함
DELETE {{host}}/note/2/delete